import { Program } from './types';

export const programs: Program[] = [
  {
    id: 'campus-leadership-summit-2024',
    title: 'Campus Leadership Summit 2024',
    description: 'Be part of focused sessions, networking, and student-led initiatives.',
    date: '24',
    month: 'MAY',
    time: '10:00 AM - 2:00 PM',
    location: 'University of Lagos',
    href: '/events/leadership-summit-2024',
    status: 'upcoming',
    category: 'Summit',
  },
  {
    id: 'career-development-webinar',
    title: 'Career Development Webinar',
    description: 'Gain practical career insights, networking tips, and professional growth strategies.',
    date: '15',
    month: 'JUN',
    time: '6:00 PM - 8:00 PM',
    location: 'Virtual (Zoom)',
    href: '/events/career-development-webinar',
    status: 'upcoming',
    category: 'Webinar',
  },
  {
    id: 'innovation-workshop-2024',
    title: 'Innovation & Design Workshop',
    description: 'Build creative solutions with hands-on sessions led by industry experts.',
    date: '05',
    month: 'APR',
    time: '9:00 AM - 1:00 PM',
    location: 'University of Ibadan',
    href: '/events/innovation-workshop-2024',
    status: 'past',
    category: 'Workshop',
  },
  {
    id: 'community-impact-hackathon',
    title: 'Community Impact Hackathon',
    description: 'Collaborate with peers to solve social challenges using technology and design thinking.',
    date: '12',
    month: 'MAR',
    time: '10:00 AM - 5:00 PM',
    location: 'Lagos Innovation Hub',
    href: '/events/community-impact-hackathon',
    status: 'past',
    category: 'Hackathon',
  },
];
