import { Leader } from './types';

export const leaders: Leader[] = [
  {
    id: 'faith-a',
    name: 'Faith A.',
    title: 'Founder / Patron',
    initials: 'FA',
    school: 'FUTMinna',
    location: 'Minna, Niger State',
    tags: ['Leadership', 'Strategy'],
    bio: 'Faith founded NSS with a vision to connect Nigerian students to space science and technology. She oversees strategic direction and partnerships.',
    quote: 'The sky is not the limit — it\'s just the beginning.',
    image: '/leaders/faith.jpg',
    email: 'faith@nss.org',
    phone: '+234 800 000 0001',
    linkedin: 'https://linkedin.com/in/faith-a',
  },
  {
    id: 'jude',
    name: 'Jude',
    title: 'President',
    initials: 'JU',
    school: 'FUTMinna',
    location: 'Minna, Niger State',
    tags: ['Operations', 'Community'],
    bio: 'Jude leads day-to-day operations and represents NSS across campus and partner institutions nationwide.',
    quote: 'Great teams are built one honest conversation at a time.',
    image: '/leaders/jude.jpg',
    email: 'jude@nss.org',
    phone: '+234 800 000 0002',
    linkedin: 'https://linkedin.com/in/jude',
  },
  {
    id: 'deborah-o',
    name: 'Deborah O.',
    title: 'Programs Director',
    initials: 'DO',
    school: 'FUTMinna',
    location: 'Minna, Niger State',
    tags: ['Programs', 'Education'],
    bio: 'Deborah designs and runs the educational programs that bring space science to students across campuses.',
    quote: 'Learning should feel like discovery, not obligation.',
    image: '/leaders/deborah.jpg',
    email: 'deborah@nss.org',
    phone: '+234 800 000 0003',
    linkedin: 'https://linkedin.com/in/deborah-o',
  },
  {
    id: 'blessing-a',
    name: 'Blessing A.',
    title: 'Communications Lead',
    initials: 'BA',
    school: 'FUTMinna',
    location: 'Minna, Niger State',
    tags: ['Communications', 'Media'],
    bio: 'Blessing manages NSS\'s voice across every platform, from social media to press outreach.',
    quote: 'Every story we tell brings someone closer to the stars.',
    image: '/leaders/blessing.jpg',
    email: 'blessing@nss.org',
    phone: '+234 800 000 0004',
    linkedin: 'https://linkedin.com/in/blessing-a',
  },
];